package envplan

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/rancher/tests/internal/agenticqa/envconfig"
	"github.com/rancher/tests/internal/agenticqa/types"
)

// Relative-path components mirroring the qa-infra-automation layout. The
// generated upstream artifacts are written at these paths (under the upstream
// output subdirectory) so they can be copied straight into a qa-infra checkout.
const (
	infraTofuDir            = "tofu"
	infraTofuModule         = "modules"
	infraTofuClusterNodes   = "cluster_nodes"
	infraTfvarsFile         = "terraform.tfvars"
	infraAnsibleDir         = "ansible"
	infraAnsibleVarsFile    = "vars.yaml"
	infraRancherSubpath     = "rancher/default-ha"
	infraSecurityGroupField = "aws_security_group"
)

// UpstreamArtifactPaths returns the qa-infra-relative paths for the three
// generated upstream files, derived from the provider/distro/env in cfg:
//   - tofu/<provider>/modules/cluster_nodes/terraform.tfvars
//   - ansible/<distro>/<env>/vars.yaml
//   - ansible/rancher/default-ha/vars.yaml
func UpstreamArtifactPaths(cfg envconfig.UpstreamConfig) (tfvars, clusterVars, rancherVars string) {
	tfvars = filepath.Join(infraTofuDir, cfg.Provider, infraTofuModule, infraTofuClusterNodes, infraTfvarsFile)
	clusterVars = filepath.Join(infraAnsibleDir, cfg.KubernetesDistro, cfg.Env, infraAnsibleVarsFile)
	rancherVars = filepath.Join(infraAnsibleDir, infraRancherSubpath, infraAnsibleVarsFile)
	return tfvars, clusterVars, rancherVars
}

// SupportsTfvars reports whether terraform.tfvars generation is supported for
// the upstream provider. Only AWS has a cluster_nodes tofu module today.
func SupportsTfvars(cfg envconfig.UpstreamConfig) bool {
	return strings.EqualFold(cfg.Provider, types.ProviderAWS)
}

// GenerateTerraformTfvars renders the qa-infra-automation terraform.tfvars for
// the upstream cluster's node topology (AWS cluster_nodes module). Non-topology
// fields come verbatim from cfg.TfvarsTemplate (typically ${VAR} placeholders).
// The nodes list is grouped by role signature; when a pool carries a resolved
// instance type it is emitted as a per-group instance_type override.
func GenerateTerraformTfvars(up types.UpstreamCluster, cfg envconfig.UpstreamConfig) ([]byte, error) {
	if !SupportsTfvars(cfg) {
		return nil, fmt.Errorf("terraform.tfvars generation is only supported for provider %q (got %q)",
			types.ProviderAWS, cfg.Provider)
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by agentic-qa plan-environment (upstream Rancher cluster).\n")
	buf.WriteString("# Mirrors qa-infra-automation tofu/aws/modules/cluster_nodes/terraform.tfvars.\n")
	buf.WriteString("# Sensitive values are ${VAR} placeholders: run `envsubst` before `tofu apply`.\n")
	fmt.Fprintf(&buf, "# Total upstream nodes: %d\n\n", up.TotalNodes)

	// Non-topology fields, sorted for determinism. aws_security_group is a list.
	for _, key := range sortedKeysStr(cfg.TfvarsTemplate) {
		val := cfg.TfvarsTemplate[key]
		if key == infraSecurityGroupField {
			fmt.Fprintf(&buf, "%s = [%s]\n", key, hclString(val))
			continue
		}
		fmt.Fprintf(&buf, "%s = %s\n", key, hclString(val))
	}

	// Volume size: prefer a resolved spec disk size, else the baseline.
	volume := cfg.BaselineVolumeSizeGiB
	if d := maxPoolDisk(up.NodePools); d > 0 {
		volume = d
	}
	if volume > 0 {
		fmt.Fprintf(&buf, "aws_volume_size = %d\n", volume)
	}

	// nodes = [ { count, role = [...], instance_type? } ]
	buf.WriteString("\nnodes = [\n")
	for _, n := range up.NodePools {
		roles := infraRoles(n)
		fmt.Fprintf(&buf, "  { count = %d, role = [%s]", maxInt(n.Quantity, 1), hclStringList(roles))
		if n.Spec != nil && n.Spec.InstanceType != "" {
			fmt.Fprintf(&buf, ", instance_type = %s", hclString(n.Spec.InstanceType))
		}
		buf.WriteString(" },\n")
	}
	buf.WriteString("]\n")

	// airgap/proxy are required variables in the module; default to false.
	buf.WriteString("\nairgap_setup = false\n")
	buf.WriteString("proxy_setup  = false\n")

	return buf.Bytes(), nil
}

// GenerateClusterVarsYAML renders the ansible cluster vars.yaml for the upstream
// distro (rke2 or k3s), carrying the kubernetes version and CNI.
func GenerateClusterVarsYAML(cfg envconfig.UpstreamConfig) ([]byte, error) {
	root := map[string]any{
		"kubernetes_version": cfg.KubernetesVersion,
		"kubeconfig_file":    "./kubeconfig.yaml",
		"node_token_file":    "/tmp/node_token.txt",
	}
	switch cfg.KubernetesDistro {
	case types.DistroK3S:
		root["server_flags"] = "protect-kernel-defaults: true\n"
		root["worker_flags"] = "protect-kernel-defaults: true\n"
		root["channel"] = "stable"
	case types.DistroRKE2, "":
		root["cni"] = cfg.CNI
		root["server_flags"] = "ingress-controller: traefik\n"
	default:
		root["cni"] = cfg.CNI
	}

	header := fmt.Sprintf("# Generated by agentic-qa plan-environment (upstream %s cluster).\n"+
		"# Mirrors qa-infra-automation ansible/%s/%s/vars.yaml.\n",
		cfg.KubernetesDistro, cfg.KubernetesDistro, cfg.Env)
	return marshalYAMLWithHeader(root, header)
}

// GenerateRancherVarsYAML renders the ansible rancher vars.yaml for the upstream
// Rancher install. It is always emitted regardless of distro.
func GenerateRancherVarsYAML(cfg envconfig.UpstreamConfig) ([]byte, error) {
	root := map[string]any{
		"rancher_version":      cfg.RancherVersion,
		"rancher_image_tag":    cfg.RancherImageTag,
		"cert_manager_version": cfg.CertManagerVersion,
		"fqdn":                 cfg.FQDN,
		"bootstrap_password":   "${RANCHER_BOOTSTRAP_PASSWORD}",
		"password":             "${RANCHER_PASSWORD}",
	}
	header := "# Generated by agentic-qa plan-environment (upstream Rancher install).\n" +
		"# Mirrors qa-infra-automation ansible/rancher/default-ha/vars.yaml.\n" +
		"# Rancher HA replica count auto-derives from the number of etcd nodes.\n"
	return marshalYAMLWithHeader(root, header)
}

// infraRoles maps a node requirement's roles to qa-infra role names
// (controlplane -> cp). Windows-only pools are treated as workers.
func infraRoles(n types.NodeRequirement) []string {
	var roles []string
	if n.Etcd {
		roles = append(roles, types.InfraRoleEtcd)
	}
	if n.ControlPlane {
		roles = append(roles, types.InfraRoleCP)
	}
	if n.Worker || n.Windows {
		roles = append(roles, types.InfraRoleWorker)
	}
	if len(roles) == 0 {
		roles = []string{types.InfraRoleWorker}
	}
	return roles
}

// maxPoolDisk returns the largest resolved disk size across pools, or 0 if no
// pool carries a recommended spec.
func maxPoolDisk(pools []types.NodeRequirement) int {
	max := 0
	for _, p := range pools {
		if p.Spec != nil && p.Spec.DiskGiB > max {
			max = p.Spec.DiskGiB
		}
	}
	return max
}

// hclString renders a Go string as an HCL double-quoted string literal.
func hclString(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
}

// hclStringList renders a slice as comma-separated HCL string literals (without
// the surrounding brackets).
func hclStringList(items []string) string {
	quoted := make([]string, len(items))
	for i, it := range items {
		quoted[i] = hclString(it)
	}
	return strings.Join(quoted, ", ")
}

// marshalYAMLWithHeader marshals a map to YAML, prefixed with a comment header.
func marshalYAMLWithHeader(v map[string]any, header string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(header)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(v); err != nil {
		_ = enc.Close()
		return nil, fmt.Errorf("encoding upstream vars yaml: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("closing yaml encoder: %w", err)
	}
	return buf.Bytes(), nil
}
