package envplan

import (
	"bytes"
	"fmt"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/rancher/tests/internal/agenticqa/envconfig"
	"github.com/rancher/tests/internal/agenticqa/types"
)

// Relative-path components mirroring the qa-infra-automation layout. The
// generated upstream artifacts are written at these paths (under the upstream
// output subdirectory) so they can be copied straight into a qa-infra checkout.
const (
	infraTofuDir            = "tofu"
	infraTofuModule         = "modules"
	infraTofuClusterNodes   = "cluster_nodes"
	infraTfvarsFile         = "terraform.tfvars"
	infraTofuEnvFile        = "tofu.env.example"
	infraAnsibleDir         = "ansible"
	infraAnsibleVarsFile    = "vars.yaml"
	infraRancherSubpath     = "rancher/default-ha"
	infraSecurityGroupField = "aws_security_group"
	infraInstanceTypeField  = "instance_type"
)

// UpstreamArtifactPaths returns the qa-infra-relative paths for the three
// generated upstream files, derived from the provider/distro/env in cfg:
//   - tofu/<provider>/modules/cluster_nodes/terraform.tfvars
//   - ansible/<distro>/<env>/vars.yaml
//   - ansible/rancher/default-ha/vars.yaml
func UpstreamArtifactPaths(cfg envconfig.UpstreamConfig) (tfvars, clusterVars, rancherVars string) {
	tfvars = filepath.Join(infraTofuDir, cfg.Provider, infraTofuModule, infraTofuClusterNodes, infraTfvarsFile)
	clusterVars = filepath.Join(infraAnsibleDir, cfg.KubernetesDistro, cfg.Env, infraAnsibleVarsFile)
	rancherVars = filepath.Join(infraAnsibleDir, infraRancherSubpath, infraAnsibleVarsFile)
	return tfvars, clusterVars, rancherVars
}

// TofuEnvFilePath returns the qa-infra-relative path for the generated
// tofu.env.example file, placed alongside terraform.tfvars in the same
// cluster_nodes module directory: tofu/<provider>/modules/cluster_nodes/tofu.env.example
func TofuEnvFilePath(cfg envconfig.UpstreamConfig) string {
	return filepath.Join(infraTofuDir, cfg.Provider, infraTofuModule, infraTofuClusterNodes, infraTofuEnvFile)
}

// SupportsTfvars reports whether terraform.tfvars generation is supported for
// the upstream provider. Only AWS has a cluster_nodes tofu module today.
func SupportsTfvars(cfg envconfig.UpstreamConfig) bool {
	return strings.EqualFold(cfg.Provider, types.ProviderAWS)
}

// GenerateTerraformTfvars renders the qa-infra-automation terraform.tfvars for
// the upstream cluster's node topology (AWS cluster_nodes module).
//
// Only topology fields (nodes, aws_volume_size, airgap_setup, proxy_setup) are
// emitted as active (uncommented) assignments. The non-topology fields
// (credentials, networking, and the global instance_type) come from
// cfg.TfvarsTemplate and are emitted as *commented-out* documentation/
// placeholders: they are intended to be supplied at `tofu apply` time via
// TF_VAR_<name> environment variables (see GenerateTofuEnvFile), not via this
// file. A `-var-file` assignment always takes precedence over a TF_VAR_
// environment variable, so leaving them commented here lets the environment
// variables take effect; uncomment a line to hardcode that value instead.
//
// The nodes list is grouped by role signature; when a pool carries a resolved
// instance type it is emitted as a per-group instance_type override.
func GenerateTerraformTfvars(up types.UpstreamCluster, cfg envconfig.UpstreamConfig) ([]byte, error) {
	if !SupportsTfvars(cfg) {
		return nil, fmt.Errorf("terraform.tfvars generation is only supported for provider %q (got %q)",
			types.ProviderAWS, cfg.Provider)
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by agentic-qa plan-environment (upstream Rancher cluster).\n")
	buf.WriteString("# Mirrors qa-infra-automation tofu/aws/modules/cluster_nodes/terraform.tfvars.\n")
	buf.WriteString("#\n")
	buf.WriteString("# Only the cluster topology (nodes, aws_volume_size, airgap_setup,\n")
	buf.WriteString("# proxy_setup) is set below as active values. The commented-out lines\n")
	buf.WriteString("# document every other variable required by the cluster_nodes module;\n")
	buf.WriteString("# supply them at `tofu apply` time via TF_VAR_<name> environment\n")
	buf.WriteString("# variables instead of uncommenting them here (see the generated\n")
	buf.WriteString("# tofu.env.example alongside this file). A -var-file assignment always\n")
	buf.WriteString("# overrides a TF_VAR_ environment variable, so keep these commented\n")
	buf.WriteString("# unless you intend to hardcode a value.\n")
	buf.WriteString("#\n")
	buf.WriteString("# Usage (run from qa-infra-automation repo root):\n")
	buf.WriteString("#   1. cp this file to tofu/aws/modules/cluster_nodes/terraform.tfvars\n")
	buf.WriteString("#   2. set -a; source tofu.env.example (filled in); set +a\n")
	buf.WriteString("#   3. make infra-up\n")
	fmt.Fprintf(&buf, "# Total upstream nodes: %d\n\n", up.TotalNodes)

	// Resolve the global (top-level) instance_type from the upstream node
	// pools' recommended specs. When resolved it is emitted as an active
	// top-level value (the module requires instance_type and uses it as the
	// default for any node group without a per-group override); otherwise it
	// falls back to the commented-out ${VAR} template line below.
	topInstanceType := upstreamInstanceType(up)

	// Non-topology fields, sorted for determinism, commented out. Values come
	// from TF_VAR_<name> environment variables at apply time. aws_security_group
	// is a list. instance_type is emitted active below when resolved, so it is
	// skipped here in that case; per-node instance_type overrides (below, in
	// `nodes`) remain active regardless.
	for _, key := range sortedKeysStr(cfg.TfvarsTemplate) {
		val := cfg.TfvarsTemplate[key]
		if key == infraInstanceTypeField && topInstanceType != "" {
			// Emitted as an active value below.
			continue
		}
		if key == infraSecurityGroupField {
			fmt.Fprintf(&buf, "# %s = [%s]\n", key, hclString(val))
			continue
		}
		fmt.Fprintf(&buf, "# %s = %s\n", key, hclString(val))
	}

	// Top-level instance_type: the resolved global default for node groups
	// without a per-group override. Emitted active when a spec resolved it.
	if topInstanceType != "" {
		fmt.Fprintf(&buf, "\ninstance_type = %s\n", hclString(topInstanceType))
	}

	// Volume size: prefer a resolved spec disk size, else the baseline. This
	// is a topology-derived value, so it is emitted active.
	volume := cfg.BaselineVolumeSizeGiB
	if d := maxPoolDisk(up.NodePools); d > 0 {
		volume = d
	}
	if volume > 0 {
		fmt.Fprintf(&buf, "aws_volume_size = %d\n", volume)
	}

	// nodes = [ { count, role = [...], instance_type? } ]
	buf.WriteString("\nnodes = [\n")
	for _, n := range up.NodePools {
		roles := infraRoles(n)
		fmt.Fprintf(&buf, "  { count = %d, role = [%s]", maxInt(n.Quantity, 1), hclStringList(roles))
		if n.Spec != nil && n.Spec.InstanceType != "" {
			fmt.Fprintf(&buf, ", instance_type = %s", hclString(n.Spec.InstanceType))
		}
		buf.WriteString(" },\n")
	}
	buf.WriteString("]\n")

	// airgap/proxy are required variables in the module; default to false.
	buf.WriteString("\nairgap_setup = false\n")
	buf.WriteString("proxy_setup  = false\n")

	return buf.Bytes(), nil
}

// tofuEnvVarDescriptions gives a short human-readable comment for each
// well-known non-topology cluster_nodes module variable. Any key present in
// cfg.TfvarsTemplate but missing from this map (e.g. a custom addition in
// pipeline_env.json) still gets emitted, with a generic fallback comment.
var tofuEnvVarDescriptions = map[string]string{
	"aws_access_key": "AWS access key ID",
	"aws_secret_key": "AWS secret access key",
	"aws_region":     "AWS region (e.g. us-east-2)",
	"aws_ami":        "AMI ID for cluster node instances",
	"aws_ssh_user":   "SSH user for the AMI (e.g. ec2-user)",
	"aws_vpc":        "VPC ID to launch instances into",
	"aws_subnet":     "Subnet ID to launch instances into",
	infraSecurityGroupField: `Security group ID(s) of an EXISTING security group (this module only ` +
		`attaches it; it does not create or manage ingress rules). It must already ` +
		`allow inbound TCP 22 from your IP (SSH) and TCP 6443/9345/10250 between ` +
		`nodes (RKE2), or Ansible will hang/timeout connecting. TF_VAR_ form must ` +
		`be an HCL/JSON list, e.g. ["sg-xxxxxxxx"]`,
	"aws_route53_zone":     "Route53 hosted zone for the cluster FQDN",
	"aws_hostname_prefix":  "Prefix for EC2 Name tags",
	"aws_volume_type":      "EBS volume type (e.g. gp3)",
	"public_ssh_key":       "Path to the public SSH key to inject into instances",
	"private_ssh_key":      "Path to the private SSH key used by Ansible to connect",
	infraInstanceTypeField: "Default/global EC2 instance type",
}

// placeholderVarPattern matches a whole-string ${VAR_NAME} placeholder, as
// used throughout envconfig's generated defaults.
var placeholderVarPattern = regexp.MustCompile(`^\$\{([A-Za-z0-9_]+)\}$`)

// shellSingleQuote wraps a value in single quotes so it is safe to `source`
// from a shell env file, regardless of characters like <, >, spaces, or $
// (single quotes suppress all shell expansion/redirection). Embedded single
// quotes are escaped using the '\” idiom.
func shellSingleQuote(val string) string {
	return "'" + strings.ReplaceAll(val, "'", `'\''`) + "'"
}

// envExamplePlaceholder converts a template value into a safe example value
// for a shell env file. ${VAR_NAME}-style placeholders are rewritten to
// <VAR_NAME>: the file is meant to be `source`d directly, and a literal
// ${VAR_NAME} would be expanded by the shell (silently becoming empty if
// VAR_NAME isn't already set) instead of prompting the user to fill it in.
// Values that aren't ${VAR}-shaped (already-literal defaults) pass through
// unchanged. The result is NOT shell-quoted; callers that emit it into an env
// file must quote it (e.g. via shellSingleQuote).
func envExamplePlaceholder(val string) string {
	if m := placeholderVarPattern.FindStringSubmatch(val); m != nil {
		return "<" + m[1] + ">"
	}
	return val
}

// envVarNameFromPlaceholder extracts the variable name from a ${VAR_NAME}
// placeholder (e.g. "${RKE2_VERSION}" -> "RKE2_VERSION"), falling back to
// fallback when val isn't shaped like a placeholder.
func envVarNameFromPlaceholder(val, fallback string) string {
	if m := placeholderVarPattern.FindStringSubmatch(val); m != nil {
		return m[1]
	}
	return fallback
}

// firstNonEmpty returns the first non-empty string from the arguments, or "".
func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}
	return ""
}

// resolveMakefileEnv resolves the qa-infra-automation Makefile's ENV variable
// value from the plan/config's deployment environment string.
//
// qa-infra-automation's Makefile computes the tofu module directory as
// tofu/<PROVIDER>/modules/<ENV> for every ENV value except "default", which is
// special-cased internally to the tofu/<PROVIDER>/modules/cluster_nodes
// module (see qa-infra-automation/Makefile's TOFU_DIR assignment). Because of
// that internal mapping:
//   - an airgapped plan must set ENV to the literal "airgap" (selects
//     tofu/<PROVIDER>/modules/airgap and the airgap ansible playbooks)
//   - an empty/unset env defaults to the literal "default" (selects
//     tofu/<PROVIDER>/modules/cluster_nodes via the Makefile's own mapping)
//   - any other qa-infra-automation environment (e.g. a future "proxy") is
//     passed through unchanged: the raw value already IS the
//     PROVIDER-specific tofu module foldername under that scheme, so no
//     separate lookup table is needed
func resolveMakefileEnv(env string) string {
	switch strings.ToLower(strings.TrimSpace(env)) {
	case "":
		return "default"
	case "airgap":
		return "airgap"
	case "default":
		return "default"
	default:
		return env
	}
}

// securityGroupTFVarList renders a concrete aws_security_group template value as
// an HCL/JSON list literal for the TF_VAR_ form. The value may already be a
// bracketed list, a single ID, or a comma-separated list of IDs.
func securityGroupTFVarList(val string) string {
	trimmed := strings.TrimSpace(val)
	if strings.HasPrefix(trimmed, "[") {
		return trimmed // already a list literal
	}
	parts := strings.Split(trimmed, ",")
	quoted := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		quoted = append(quoted, `"`+p+`"`)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// GenerateTofuEnvFile renders a combined env-file template for supplying the
// non-topology cluster_nodes module variables (credentials/networking) plus
// the ansible-stage placeholders (RKE2/K3s + Rancher install parameters) at
// `tofu apply` / ansible-playbook time, without editing terraform.tfvars.
//
// Non-sensitive values that the environment plan resolves concretely (e.g. the
// global instance_type, kubernetes/CNI/distro-derived values) are pre-filled;
// sensitive or site-specific values (credentials, VPC/subnet/security-group
// IDs, SSH key paths, passwords) are emitted as <PLACEHOLDER> for the operator.
//
// Each tofu variable is emitted in both forms:
//   - TF_VAR_<name>=... (read automatically by `tofu`/`terraform` commands,
//     including via `make infra-up`)
//   - <name>=...        (plain form, for tooling that expects unprefixed
//     names, e.g. manual envsubst of the ansible vars.yaml files)
//
// The file is meant to be filled in and sourced on the host machine before
// running `make infra-up` / `make cluster` / `make rancher`:
//
//	set -a; source tofu.env.example; set +a
func GenerateTofuEnvFile(up types.UpstreamCluster, cfg envconfig.UpstreamConfig) ([]byte, error) {
	// Concrete non-sensitive values resolved from the environment plan, keyed by
	// tfvars var. These take precedence over the (typically ${VAR}) template.
	resolved := map[string]string{}
	if it := upstreamInstanceType(up); it != "" {
		resolved[infraInstanceTypeField] = it
	}
	// Note: aws_volume_size is topology and is written directly (active) in
	// terraform.tfvars, so it is intentionally NOT surfaced here -- a -var-file
	// assignment overrides any TF_VAR_aws_volume_size anyway.

	var buf bytes.Buffer
	buf.WriteString("# Generated by agentic-qa plan-environment (upstream Rancher cluster).\n")
	buf.WriteString("#\n")
	buf.WriteString("# Non-sensitive values identified by the environment plan are pre-filled\n")
	buf.WriteString("# below. Fill in the remaining placeholder (<...>) values (credentials,\n")
	buf.WriteString("# VPC/subnet/security-group IDs, SSH key paths, passwords), then source\n")
	buf.WriteString("# this file before running qa-infra-automation's Makefile targets:\n")
	buf.WriteString("#\n")
	buf.WriteString("#   set -a; source tofu.env.example; set +a\n")
	buf.WriteString("#   make infra-up   # tofu apply + inventory generation\n")
	buf.WriteString("#   make cluster    # install RKE2/K3s\n")
	buf.WriteString("#   make rancher    # install Rancher\n")
	buf.WriteString("#\n")
	buf.WriteString("# Each cluster_nodes module variable is listed twice: once with the\n")
	buf.WriteString("# TF_VAR_ prefix (consumed automatically by `tofu`/`terraform`, and\n")
	buf.WriteString("# therefore by `make infra-up`) and once without (for tooling that\n")
	buf.WriteString("# expects the plain name, e.g. manual envsubst of ansible vars.yaml).\n")
	buf.WriteString("# Keep both in sync.\n")
	buf.WriteString("#\n")
	buf.WriteString("# NOTE: terraform.tfvars sets the cluster topology (nodes, instance_type,\n")
	buf.WriteString("# aws_volume_size, airgap_setup, proxy_setup) directly. A -var-file\n")
	buf.WriteString("# assignment always overrides a TF_VAR_ environment variable, so the\n")
	buf.WriteString("# variables below stay commented out in terraform.tfvars.\n\n")

	buf.WriteString("# --- environment plan (identified) ---\n")
	buf.WriteString("# PROVIDER/ENV match qa-infra-automation's Makefile variables directly,\n")
	buf.WriteString("# e.g. `make infra-up PROVIDER=$PROVIDER ENV=$ENV`.\n\n")
	if provider := firstNonEmpty(up.Provider, cfg.Provider); provider != "" {
		fmt.Fprintf(&buf, "# Cloud/node provider\n")
		fmt.Fprintf(&buf, "PROVIDER=%s\n\n", shellSingleQuote(provider))
	}
	fmt.Fprintf(&buf, "# qa-infra-automation deployment environment: \"airgap\" when the plan\n")
	fmt.Fprintf(&buf, "# is airgapped, \"default\" otherwise, or the PROVIDER-specific tofu\n")
	fmt.Fprintf(&buf, "# module foldername (tofu/<PROVIDER>/modules/<ENV>) for any other\n")
	fmt.Fprintf(&buf, "# qa-infra-automation environment (e.g. \"proxy\").\n")
	fmt.Fprintf(&buf, "ENV=%s\n\n", shellSingleQuote(resolveMakefileEnv(firstNonEmpty(up.Env, cfg.Env))))

	buf.WriteString("# --- cluster_nodes tofu module variables (aws/modules/cluster_nodes) ---\n\n")
	for _, key := range sortedKeysStr(cfg.TfvarsTemplate) {
		desc, ok := tofuEnvVarDescriptions[key]
		if !ok {
			desc = fmt.Sprintf("Value for %s", key)
		}
		fmt.Fprintf(&buf, "# %s\n", desc)

		// Pre-fill precedence:
		//   1. a concrete value the plan resolved (e.g. instance_type from the
		//      recommended node specs)
		//   2. a concrete literal already set in the tfvars template (i.e. not a
		//      ${VAR} placeholder) -- reflect the plan/config verbatim
		//   3. otherwise a <PLACEHOLDER> for the operator to fill in
		// All RHS values are single-quoted so the file is safe to `source`
		// (placeholders contain <, > which the shell would treat as redirection).
		if val, found := resolved[key]; found {
			q := shellSingleQuote(val)
			fmt.Fprintf(&buf, "TF_VAR_%s=%s\n", key, q)
			fmt.Fprintf(&buf, "%s=%s\n\n", key, q)
			continue
		}

		tmpl := cfg.TfvarsTemplate[key]
		isPlaceholder := placeholderVarPattern.MatchString(tmpl)

		if key == infraSecurityGroupField {
			if !isPlaceholder && tmpl != "" {
				// Concrete list value from config: reflect it verbatim.
				fmt.Fprintf(&buf, "TF_VAR_%s=%s\n", key, shellSingleQuote(securityGroupTFVarList(tmpl)))
				fmt.Fprintf(&buf, "%s=%s\n\n", key, shellSingleQuote(tmpl))
				continue
			}
			placeholder := envVarNameFromPlaceholder(tmpl, "AWS_SECURITY_GROUP_ID")
			// TF_VAR_ form must be an HCL/JSON list literal; single-quote the
			// whole thing so brackets/quotes survive sourcing.
			fmt.Fprintf(&buf, "TF_VAR_%s=%s\n", key, shellSingleQuote(fmt.Sprintf(`["<%s>"]`, placeholder)))
			fmt.Fprintf(&buf, "%s=%s\n\n", key, shellSingleQuote(fmt.Sprintf("<%s>", placeholder)))
			continue
		}
		example := shellSingleQuote(envExamplePlaceholder(tmpl))
		fmt.Fprintf(&buf, "TF_VAR_%s=%s\n", key, example)
		fmt.Fprintf(&buf, "%s=%s\n\n", key, example)
	}

	buf.WriteString("# --- ansible vars.yaml values (cluster + rancher install) ---\n")
	buf.WriteString("# Non-sensitive values identified by the plan are pre-filled.\n\n")

	// Non-sensitive ansible values resolved directly from the plan.
	distro := firstNonEmpty(up.KubernetesDistro, cfg.KubernetesDistro)
	cni := firstNonEmpty(up.CNI, cfg.CNI)
	fmt.Fprintf(&buf, "# Kubernetes distro (rke2/k3s)\n")
	fmt.Fprintf(&buf, "KUBERNETES_DISTRO=%s\n\n", shellSingleQuote(distro))
	fmt.Fprintf(&buf, "# CNI plugin\n")
	fmt.Fprintf(&buf, "CNI=%s\n\n", shellSingleQuote(cni))

	// The management-cluster k8s version comes from the plan/config. Prefer the
	// upstream cluster's version, then the config; either may be a ${VAR}.
	k8sVersion := firstNonEmpty(up.KubernetesVersion, cfg.KubernetesVersion)
	ansibleVars := []struct {
		Fallback, Val, Description string
	}{
		{"KUBERNETES_VERSION", k8sVersion, "Kubernetes distro version (rke2/k3s vars.yaml)"},
		{"RANCHER_VERSION", cfg.RancherVersion, "Rancher chart version"},
		{"RANCHER_IMAGE_TAG", cfg.RancherImageTag, "Rancher image tag"},
		{"CERT_MANAGER_VERSION", cfg.CertManagerVersion, "cert-manager chart version"},
		{"RANCHER_FQDN", cfg.FQDN, "FQDN for the Rancher install"},
		{"RANCHER_BOOTSTRAP_PASSWORD", "${RANCHER_BOOTSTRAP_PASSWORD}", "Rancher bootstrap password"},
		{"RANCHER_PASSWORD", "${RANCHER_PASSWORD}", "Rancher admin password"},
	}
	for _, v := range ansibleVars {
		name := envVarNameFromPlaceholder(v.Val, v.Fallback)
		example := shellSingleQuote(envExamplePlaceholder(v.Val))
		fmt.Fprintf(&buf, "# %s\n", v.Description)
		fmt.Fprintf(&buf, "%s=%s\n\n", name, example)
	}

	return buf.Bytes(), nil
}

// GenerateClusterVarsYAML renders the ansible cluster vars.yaml for the upstream
// distro (rke2 or k3s), carrying the kubernetes version and CNI.
func GenerateClusterVarsYAML(cfg envconfig.UpstreamConfig) ([]byte, error) {
	root := map[string]any{
		"kubernetes_version": cfg.KubernetesVersion,
		"kubeconfig_file":    "./kubeconfig.yaml",
		"node_token_file":    "/tmp/node_token.txt",
	}
	switch cfg.KubernetesDistro {
	case types.DistroK3S:
		root["server_flags"] = "protect-kernel-defaults: true\n"
		root["worker_flags"] = "protect-kernel-defaults: true\n"
		root["channel"] = "stable"
	case types.DistroRKE2, "":
		root["cni"] = cfg.CNI
		root["server_flags"] = "ingress-controller: traefik\n"
	default:
		root["cni"] = cfg.CNI
	}

	header := fmt.Sprintf("# Generated by agentic-qa plan-environment (upstream %s cluster).\n"+
		"# Mirrors qa-infra-automation ansible/%s/%s/vars.yaml.\n",
		cfg.KubernetesDistro, cfg.KubernetesDistro, cfg.Env)
	return marshalYAMLWithHeader(root, header)
}

// GenerateRancherVarsYAML renders the ansible rancher vars.yaml for the upstream
// Rancher install. It is always emitted regardless of distro.
func GenerateRancherVarsYAML(cfg envconfig.UpstreamConfig) ([]byte, error) {
	root := map[string]any{
		"rancher_version":      cfg.RancherVersion,
		"rancher_image_tag":    cfg.RancherImageTag,
		"cert_manager_version": cfg.CertManagerVersion,
		"fqdn":                 cfg.FQDN,
		"bootstrap_password":   "${RANCHER_BOOTSTRAP_PASSWORD}",
		"password":             "${RANCHER_PASSWORD}",
	}
	header := "# Generated by agentic-qa plan-environment (upstream Rancher install).\n" +
		"# Mirrors qa-infra-automation ansible/rancher/default-ha/vars.yaml.\n" +
		"# Rancher HA replica count auto-derives from the number of etcd nodes.\n"
	return marshalYAMLWithHeader(root, header)
}

// infraRoles maps a node requirement's roles to qa-infra role names
// (controlplane -> cp). Windows-only pools are treated as workers.
func infraRoles(n types.NodeRequirement) []string {
	var roles []string
	if n.Etcd {
		roles = append(roles, types.InfraRoleEtcd)
	}
	if n.ControlPlane {
		roles = append(roles, types.InfraRoleCP)
	}
	if n.Worker || n.Windows {
		roles = append(roles, types.InfraRoleWorker)
	}
	if len(roles) == 0 {
		roles = []string{types.InfraRoleWorker}
	}
	return roles
}

// upstreamInstanceType returns the resolved global instance type for the
// cluster's node pools: the instance type of the largest resolved pool (by
// vCPU, then memory), so the top-level default covers the most demanding node
// group that lacks its own override. Returns "" when no pool carries a
// resolved instance type (e.g. --recommend-specs was not used).
func upstreamInstanceType(up types.UpstreamCluster) string {
	best := ""
	bestVCPUs, bestMem := -1, -1
	for _, p := range up.NodePools {
		if p.Spec == nil || p.Spec.InstanceType == "" {
			continue
		}
		if p.Spec.VCPUs > bestVCPUs ||
			(p.Spec.VCPUs == bestVCPUs && p.Spec.MemoryGiB > bestMem) {
			best = p.Spec.InstanceType
			bestVCPUs = p.Spec.VCPUs
			bestMem = p.Spec.MemoryGiB
		}
	}
	return best
}

// maxPoolDisk returns the largest resolved disk size across pools, or 0 if no
// pool carries a recommended spec.
func maxPoolDisk(pools []types.NodeRequirement) int {
	max := 0
	for _, p := range pools {
		if p.Spec != nil && p.Spec.DiskGiB > max {
			max = p.Spec.DiskGiB
		}
	}
	return max
}

// hclString renders a Go string as an HCL double-quoted string literal.
func hclString(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
}

// hclStringList renders a slice as comma-separated HCL string literals (without
// the surrounding brackets).
func hclStringList(items []string) string {
	quoted := make([]string, len(items))
	for i, it := range items {
		quoted[i] = hclString(it)
	}
	return strings.Join(quoted, ", ")
}

// marshalYAMLWithHeader marshals a map to YAML, prefixed with a comment header.
func marshalYAMLWithHeader(v map[string]any, header string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(header)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(v); err != nil {
		_ = enc.Close()
		return nil, fmt.Errorf("encoding upstream vars yaml: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("closing yaml encoder: %w", err)
	}
	return buf.Bytes(), nil
}
